name: Intermediate dispatch

on:
 pull_request:
    types: [assigned]
    branches:
      - continuous_integration
jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: Intermediate dispatch
      working-directory: ./phis2-ws
      run: curl http://proxmox15.asa-showroom.com/intermediate-dispatcher.php\?sha=${{ github.event.pull_request.head.sha }}\&ref\=${{ github.event.pull_request.head.ref }}\&repo__clone_url\=${{ github.event.pull_request.head.repo.clone_url }}
