name: Java CI

on:
 pull_request:
    types: [assigned]
    branches:
      - continuous_integration
jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: Informations
      run: |
          echo "env: ${{ toJson(env) }}"
          echo "github.event.pull_reques: ${{ toJson(github.event.pull_request) }}"
          echo "github.event: ${{ toJson(github.event) }}"
          echo "github t: ${{ toJson(github.token) }}"
          echo "dollar_secrets:  '"${{secrets}}"'    "
          echo "secrets: ${{ toJson(secrets) }}"
          echo "github:: ${{ toJson(github) }}"
          echo
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      working-directory: ./phis2-ws
      run: curl http://proxmox15.asa-showroom.com/intermediate-dispatcher.php?sha=(github.event.pull_reques.head.sha)&ref=(github.event.pull_reques.head.ref)
